### ISSUE TITLE
Fix Edge Cases for Pong

### ISSUE THREAD

**Issue by ayushbasak** [ayushbasak/ponghub#1]
Hi! I created this pong like game when I was playing with p5.js.
One has to hit the ball with a paddle, and the ball gets faster.

#### Issue: 
There are times when the ball just passes over the paddle, when it is considerably fast. And sometimes the ball would bounce from the paddle even though it did not hit it.

**Comment by cf12** [comment]
Hey! I can try to work on this.

**Comment by ayushbasak** [comment]
A couple of lines of js might fix this, but sure go ahead! 🙂
